### ISSUE TITLE
Hair layers for Persephone are handled incorreectly

### ISSUE THREAD

**Issue by h4l** [h4l/headgear#30]
A [user reports](https://www.reddit.com/r/avatartrading/comments/10eekoo/comment/j5rdl47/?context=3):
> I've noticed an issue trying to export Persephone, the hair is the wrong colour and scale, see attached:
>
> ![image](https://user-images.githubusercontent.com/146503/214499150-90dbe214-1666-4eff-978b-6f33be1ab197.png)

Should look like this:
<img width="820" alt="image" src="https://user-images.githubusercontent.com/146503/214499365-7f486225-720e-4186-959f-cfc48e87c6df.png">

**Comment by h4l** [comment]
[u/SpiceWeaselBAM](https://www.reddit.com/user/SpiceWeaselBAM/) kindly helped me debug this by generating and sharing an SVG file for Persephone. The problem seems to be that the back and front hair layers have different CSS styles, and fail to isolate the styles when merging layer CSS styles:

```css
/* genuineardvark_cp2_hair_002 */
.genuineardvark_cp2_hair_002-cls-1,.genuineardvark_cp2_hair_002-cls-2{fill:#fff;}
.genuineardvark_cp2_hair_002-cls-1{opacity:0.48;}
.genuineardvark_cp2_hair_002-cls-3,.genuineardvark_cp2_hair_002-cls-5,.genuineardvark_cp2_hair_002-cls-6,.genuineardvark_cp2_hair_002-cls-7{fill:#f05858;}
.genuineardvark_cp2_hair_002-cls-4{fill:#38223d;}
.genuineardvark_cp2_hair_002-cls-5{opacity:0.47;}
.genuineardvark_cp2_hair_002-cls-6{opacity:0.31;}
.genuineardvark_cp2_hair_002-cls-7{opacity:0.64;}
.genuineardvark_cp2_hair_002-cls-8{fill:#f8b6b6;}
.genuineardvark_cp2_hair_002-cls-11,.genuineardvark_cp2_hair_002-cls-9{fill:none;stroke-miterlimit:10;}
.genuineardvark_cp2_hair_002-cls-9{stroke:#f8b6b6;stroke-width:1.83px;}
.genuineardvark_cp2_hair_002-cls-10{fill:#f48b8b;}
.genuineardvark_cp2_hair_002-cls-11{stroke:#f48b8b;stroke-width:2px;}
.genuineardvark_cp2_hair_002-cls-12{fill:#331538;}
.genuineardvark_cp2_hair_002-cls-13{fill:#a774b1;}

/* genuineardvark_cp2_hair_002 */
.genuineardvark_cp2_hair_002-cls-1{fill:#38223d;}
.genuineardvark_cp2_hair_002-cls-2{fill:#a774b1;}
.genuineardvark_cp2_hair_002-cls-3{fill:#8b53a0;}
.genuineardvark_cp2_hair_002-cls-12,.genuineardvark_cp2_hair_002-cls-4{fill:#fff;}
.genuineardvark_cp2_hair_002-cls-10,.genuineardvark_cp2_hair_002-cls-11,.genuineardvark_cp2_hair_002-cls-5,.genuineardvark_cp2_hair_002-cls-6,.genuineardvark_cp2_hair_002-cls-7,.genuineardvark_cp2_hair_002-cls-8,.genuineardvark_cp2_hair_002-cls-9{fill:none;stroke:#a774b1;stroke-miterlimit:10;}
.genuineardvark_cp2_hair_002-cls-5{stroke-width:1.5px;}
.genuineardvark_cp2_hair_002-cls-6{stroke-width:1.42px;}
.genuineardvark_cp2_hair_002-cls-7{stroke-width:1.31px;}
.genuineardvark_cp2_hair_002-cls-8{stroke-width:0.87px;}
.genuineardvark_cp2_hair_002-cls-9{stroke-width:1.12px;}
.genuineardvark_cp2_hair_002-cls-10{stroke-width:0.75px;}
.genuineardvark_cp2_hair_002-cls-11{stroke-width:2px;}
.genuineardvark_cp2_hair_002-cls-12{opacity:0.38;}
.genuineardvark_cp2_hair_002-cls-13{fill:#cfa2ca;opacity:0.56;}
```

We need to namespace the styles by something in addition to layer name, as the layer name is repeated in situations like hair where there are back and front layers for the same logical accessory.
